name: Self-Hosted Runner Workflow

on:
  push:
    branches:
      - master

jobs:
  run-on-macos:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run date command
      run: date

    - name: Run whoami command
      run: whoami

  run-on-ec2:
    runs-on: Linux

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run date command
      run: date

    - name: Run whoami command
      run: whoami

